#spring.security.user.name= Basant
#spring.security.user.password= Pwd1

server:
  port: 8081
spring:
  application:
    name: Loung
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/java-spring-security-test
    username: root
    password:
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    change-log: classpath:config/liquibase/master.xml
    drop-first: false
    contexts: dev
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

